SELECT
  SC.SCHEDULERDATAID,
  SC.START,
  SC.FINISH,
  SC.RESOURCEID,
  SC.MESSAGE,
  SC.DEMOGID,
  SC.DELETED,
  SC.WARDID,
  SR.NAME,
  SR.LABORATORYID,
  SR.ISACTIVE,
  D.DEMOGID,
  D.LNAME,
  D.FNAME,
  D.MOBILE,
  D.EMAIL,
  L.LABORATORYID,
  L.FNAME,
  L.ADDRESS,
  SM.EXAMSTRCODE
FROM
  [SLIS-SQL-SRV].LISKOSMO.DBO.SCHEDULERDATA AS SC
WITH
  (NOLOCK)
  INNER JOIN [SLIS-SQL-SRV].LISKOSMO.DBO.SCHEDULERRESOURCES AS SR
WITH
  (NOLOCK) ON SR.SCHEDULERRESOURCESID = SC.RESOURCEID
  INNER JOIN [SLIS-SQL-SRV].LISKOSMO.DBO.DEMOG AS D
WITH
  (NOLOCK) ON D.DEMOGID = SC.DEMOGID
  INNER JOIN [SLIS-SQL-SRV].LISKOSMO.DBO.LABORATORY AS L ON L.LABORATORYID = SR.LABORATORYID
  INNER JOIN [SLIS-SQL-SRV].LISKOSMO.DBO.SCHEDULERDATAEXAM AS SM
WITH
  (NOLOCK) ON SM.SCHEDULERDATAID = SC.SCHEDULERDATAID
WHERE
  CAST([START] AS DATE) = @DATE
  AND SC.DEMOGID IS NOT NULL
  AND SC.DELETED = 0